### ISSUE TITLE
Work on updated release

### ISSUE THREAD

**Issue by SamMorrowDrums** [sorribas/phantom-render-stream#106]
Created [fork of the repo](https://github.com/SamMorrowDrums/phantom-render-stream), and merged the outstanding PRs. Feel free to have a look. I'm hoping to get it ready for release, and make a PR back to you soon, then all you need to do is release it :-D Hope that works for you.

Started from chat regarding #92

**Comment by markstos** [comment]
As another user of this module, thanks for taking this on!  In addition to the PRs, did you also check out the "network" tab? There are some interesting commits on forks out there to consider. Some people may have realized the project wasn't particularly active so decided not to bother with PRs. Here's the overview page:

https://github.com/e-conomic/phantom-render-stream/network

Here are some commits on branches I found there which might be interesting:

  * [Update debug dependencies](https://github.com/blendlabs/phantom-render-stream/commit/ea70dc8ee44d6e766f01017567f84888614a1710)
 * [support localStorage](https://github.com/richpressler/phantom-render-stream/commit/96b3bbe8edd010bd10652cd4b7d25cfdd3942961) *patch is too big and messy to accept, but interesting idea!*
 * [bump phantomjs-prebuilt dependency](https://github.com/appsumo/phantom-render-stream/commit/3d66f225f51543f6a71cccfc97683d3c99e1ee75)
 * [add listen option for interface binding](https://github.com/psi-4ward/phantom-render-stream/commit/99ebbaedd80f0a3a1d023c9c2dc10a17c41b9b59) This is a security/safety issue to limit listening to just 127.0.0.1 vs 0.0.0.0, which would allow external connections, too. 

Also, it's helpful to update HISTORY.md to help people see what changed and decide if they should upgrade. 

Thanks!

**Comment by SamMorrowDrums** [comment]
This is being looked at in current PR #108
